1.0.0 release bugfix.
Summary:
The 1.0.0 release included the following warning:

    components/Switch/src/MDCSwitch.m:223:11: error: parameter 'toggleState' not found in the function declaration [-Werror,-Wdocumentation]

This was resolved in `develop`, so we're back-porting the fix to the 1.0.0 release.

Cherry-picked from http://codereview.cc/D204: [Switch] Remove internal docs demarcated with /**.

Reviewers: ajsecord, randallli, #mdc_ios_owners, iangordon

Reviewed By: #mdc_ios_owners, iangordon

Projects: #material_components_ios

Differential Revision: http://codereview.cc/D212